### ISSUE TITLE
Relative and symlink paths fail on initial build

### ISSUE THREAD

**Issue by ryderblue** [droundy/fac#17]
Due to the way Fac hashes file paths to uniquely identify targets, any use of relative, absolute, or symlink file paths will confuse the initial build. This becomes quite annoying for larger builds which have to run subsequent times. 

I think if Fac canonicalizes the file paths prior to hashing targets then this could be avoided. The problem with canonicalization using `realpath()` is that the path must exist, which isn't the case for initial builds.

See pull request #16 for test case.

**Comment by droundy** [comment]
Can you split this into separate issues? I'm not sure how to do that.  But I think handling symlinks is a distinct problem, albeit related, from handling relative paths.  Specifically, handling relative paths can be done simply knowing the working directory, while symlinks require looking at the filesystem.

**Comment by droundy** [comment]
I am looking this and now understand this issue better.  Simply canonicalizing prior to hashing won't work, since we don't repeatedly check for a file's existence (and hash), so the canonicalization wouldn't end up happening.  Instead it looks like I need to check at the very end (after we've built everything we can, so far) to see if the canonicalization has changed, and if so then try again.

The complexity here is that we only recheck whether we can build a rule after one of its inputs has been modified or created, but we don't do this by repeatedly checking its inputs (which could scale poorly), but instead by tracking files that are output by other commands, and then we rebuild any rules that depend on those files (using a table of "child" rules).
